### ISSUE TITLE
三个手指推了看不到我放进private的zip档

### ISSUE THREAD

**Issue by rawrico** [xiaogdgenuine/kedamanga-web#11]
你好，当这个功能推出了我就先试试看了
3指望上推了输入密码后
什么都没有出现
是做错了什么？
还是怎样？
再来试试3指往下推可是什么都没有

**Comment by xiaogdgenuine** [comment]
你好，可以给我提供一个录屏吗？

正常来讲是会进入隐私库的，三指上滑打开，下滑关闭。

你也可以添加我微信提供细节，在设置，关于可达漫画里有我的微信号。

**Comment by rawrico** [comment]
已经加了你的号
之后请你确认一下
到时候会发送录屏给你
