### ISSUE TITLE
删除漫画后依然有残留？

### ISSUE THREAD

**Issue by swhoro** [xiaogdgenuine/kedamanga-web#15]
系统是ipados 15 beta 
通过http服务器从电脑上传了jojo第7部到pad上，看完之后删除所有漫画，但是设置里面显示依然占用了空间：
![IMG_0028](https://user-images.githubusercontent.com/34229589/130176745-66ea8a64-5e69-46da-8334-6097e7e7cf61.PNG)
<img width="1194" alt="3" src="https://user-images.githubusercontent.com/34229589/130176810-ce41c591-2db8-4250-892c-db030dbca333.png">

**Comment by xiaogdgenuine** [comment]
这个应该是看漫画过程中产生的缓存噢（缩略图，压缩包解压后的内容等等），你可以通过「设置 - 缓存 - 清除本地缓存」来释放这部分空间。

**Comment by swhoro** [comment]
> 这个应该是看漫画过程中产生的缓存噢（缩略图，压缩包解压后的内容等等），你可以通过「设置 - 缓存 - 清除本地缓存」来释放这部分空间。

清理过了，还是占用8个多G
![IMG_0030](https://user-images.githubusercontent.com/34229589/130240702-5ec39817-89a5-4072-9540-5f05fa66a92b.PNG)
包括其他下面几个清理也都点了

**Comment by xiaogdgenuine** [comment]
我仔细检查了我的代码，可以肯定缓存是会被清理掉的，真机（iOS 14.4）也无法复现这个问题。

所以有概率是 iOS 15 beta 的 bug，没有及时更新最新的占用情况。
另外你也可以用系统自带的「文件」应用，检查一下「可达漫画」的文件夹里有没有什么残留文件，有的话删除掉试试看？

我会在 iOS 15 正式版发布后再来检查这个问题， 目前如果你实在介意，可以删掉可达重装。

**Comment by swhoro** [comment]
> 另外你也可以用系统自带的「文件」应用，检查一下「可达漫画」的文件夹里有没有什么残留文件，有的话删除掉试试看？

谢谢，文件 里面也是空的
之前用documents传文件之后删除也会有残留，怀疑确实有可能是15的bug
