### ISSUE TITLE
导入的漫画变模糊了？

### ISSUE THREAD

**Issue by Sora404** [xiaogdgenuine/kedamanga-web#16]
下载的漫画导入后就变模糊了，开了画质优化效果也不太好，但是用其他软件打开就很清晰，可能是什么原因呢？怎么解决哇

**Comment by xiaogdgenuine** [comment]
可以发我一份问题文件吗？方便我重现问题。

我的微信是
a421654151

邮箱是
xiaogdgenuine@gmail.com
