### ISSUE TITLE
无法连接基于apache的webdav服务器

### ISSUE THREAD

**Issue by AlfredQingyao** [xiaogdgenuine/kedamanga-web#17]
webdav服务用的是docker：apachewebdav/apachewebdav（http模式），连接时app内提示为401错误。
而在同设备上使用浏览器或者documents等第三方文件管理器均能正常连接

**Comment by xiaogdgenuine** [comment]
请加我微信细聊这个配置问题，这个 Repo 只是作为未来的官网项目，在这里提 issue 我回复很不及时的请见谅。

我的微信号在「设置」「支持」里有。
