### ISSUE TITLE
webdav显示错误，局域网其它设备浏览器可以访问，可达漫画访问不了

### ISSUE THREAD

**Issue by vanish1008** [xiaogdgenuine/kedamanga-web#28]
如图
![IMG_1275](https://github.com/user-attachments/assets/c3831121-4769-459a-b07d-ed3dd809930c)

**Comment by xiaogdgenuine** [comment]
感谢反馈，这个报错的意思是 405 Method not allowed，也就是 Http 方法不允许的意思，可达的 WebDAV 会发送一个 PROPFIND 请求到 WebDAV 服务器去尝试连接，遇到这个报错大概率是路径没填对，访问的地址不支持 PROPFIND 请求导致的。

你用什么服务搭建的 WebDAV 呢？可以加一下我微信 a421654151，我给你定位一下问题所在。

**Comment by vanish1008** [comment]
> 感谢反馈，这个报错的意思是 405 Method not allowed，也就是 Http 方法不允许的意思，可达的 WebDAV 会发送一个 PROPFIND 请求到 WebDAV 服务器去尝试连接，遇到这个报错大概率是路径没填对，访问的地址不支持 PROPFIND 请求导致的。
> 
> 你用什么服务搭建的 WebDAV 呢？ 可以加一下我微信 a421654151，我给你定位一下问题所在。

已解决，我用cute http file server搭建的，路径需要加/webdav
