### ISSUE TITLE
老铁， PDF 漫画无法看

### ISSUE THREAD

**Issue by wangguancong** [xiaogdgenuine/kedamanga-web#4]
找了好久，终于发现一个靠谱的IOS 漫画应用； 
不过  我PDF 的漫画 上传后 打开 都是001.jpg 这种   没办法打开

**Comment by wangguancong** [comment]
另外   老铁   我也有很多漫画  希望有共享资源

**Comment by xiaogdgenuine** [comment]
谢谢反馈，这周有事回复晚了见谅。

PDF 查看功能目前是基于 iOS 系统自带的 PDF 组件定制化实现的，确实实现得比较简单，偶尔还会奔溃，接下来的版本会重点优化。

不过你提到的 001.jpg 打不开这个问题我无法重现，方便的话可以提供一个示例文件吗？

**Comment by wangguancong** [comment]
![f3468899bc82bebf755709eabe4037b](https://user-images.githubusercontent.com/39519131/112090301-43af0700-8bce-11eb-863f-e2c34c803930.jpg)
 这个是打开后的效果     示例文件  方便留邮箱吗

**Comment by xiaogdgenuine** [comment]
@wangguancong 好的，我的邮箱是 xiaogdgenuine@gmail.com

这个情况可能是 PDF 加密了？目前确实还不支持加密的 PDF，下一个版本很快会加上。

**Comment by wangguancong** [comment]
没有加密，   偶尔有几页可以打开  稍后发您文件

**Comment by wangguancong** [comment]
https://ws28.cn/f/50724abgs6g

**Comment by wangguancong** [comment]
邮箱发不出去：   https://ws28.cn/f/50724abgs6g    链接是示例文件   1天有效

**Comment by xiaogdgenuine** [comment]
@wangguancong 已确定 PDF 可以正常显示，只是因为你的这个 PDF 图片分辨率较高，所以我原有的方法生成页面会很慢，等7，8秒那种，内存占用率也很高容易闪退。

最新版本我已经换了另一种比较高效的方式实现 PDF 阅读，基本解决了这种高清 PDF 的性能问题，预计最快会在下周发布，到时候记得更新~

**Comment by xiaogdgenuine** [comment]
@wangguancong  新版已发布，欢迎继续测试反馈。

**Comment by wangguancong** [comment]
已经解决
