### ISSUE TITLE
大图裁剪有时候会出现裁剪不准确的情况   

### ISSUE THREAD

**Issue by wangguancong** [xiaogdgenuine/kedamanga-web#6]
这个是原图
![QQ截图20210405114035](https://user-images.githubusercontent.com/39519131/113534602-c50d8d00-9603-11eb-90d2-a8e700e590c7.png)
  这个是手机上看到的裁剪后的图片  
![QQ截图20210405114144](https://user-images.githubusercontent.com/39519131/113534653-ed958700-9603-11eb-9f36-1e60eca2558e.png)

最右边丢失了一截

**Comment by xiaogdgenuine** [comment]
确实有这个问题，抱歉发布前没有在 iPhone 上仔细测试，只测试了 iPad 这种大屏设备，我很快会修复它，多谢反馈！

**Comment by xiaogdgenuine** [comment]
@wangguancong 新版已发布，麻烦你再试试看

**Comment by wangguancong** [comment]
感谢作者，虽然个别页码还有一些裁剪丢掉一个小边的情况，但是对体验基本没有影响；

**Comment by xiaogdgenuine** [comment]
客气了 :)，这个 App 现在最需要的就是大家多多反馈改进，不然将来怎么能做到「最好的 iOS 漫画阅读器」呢哈哈。

觉得好用的话可以去 AppStore 留个好评~让更多人了解到这个 App~多谢了~

**Comment by wangguancong** [comment]
必须的，，，五星好评，绝不分期
