### ISSUE TITLE
会考虑支持mobi格式的电子书嘛

### ISSUE THREAD

**Issue by wangguancong** [xiaogdgenuine/kedamanga-web#7]

**Comment by xiaogdgenuine** [comment]
@wangguancong 看了两天 Mobi 的文件规范，终于实现了一版，完美支持绝大部分 Mobi 文件。

新版本已提交，等审核，开着自动更新吧~

**Comment by xiaogdgenuine** [comment]
@wangguancong 通过审核了，快去体验吧。
觉得好用的话麻烦多多安利噢~

**Comment by wangguancong** [comment]
完美支持!!!!!!!!    大佬牛逼
