### ISSUE TITLE
漫画显示方式  退出APP后  没有记录

### ISSUE THREAD

**Issue by wangguancong** [xiaogdgenuine/kedamanga-web#8]
由于导入的漫画太多，切换成列表格式显示；  退出后 又变成了网格模式

**Comment by xiaogdgenuine** [comment]
嗯嗯，我正在给开发一个基本的文件管理功能，到时候你可以手动创建文件夹，也可以给不同漫画打不同 tag，你提的这个反馈很好，我会把它也加进去的~
